maps = {
    'en': {
        0: {'repr': ['s', 'z', 'soft c'],
            'mnemonic': '"z" is the first letter of zero. The other letters have a similar sound.'},
        1: {'repr': ['t', 'd', 'th'],
            'mnemonic': 't & d have one downstroke and sound similar (some variant systems omit "th")'},
        2: {'repr': ['n'],
            'mnemonic': 'n has two downstrokes'},
        3: {'repr': ['m'],
            'mnemonic': 'M has three downstrokes and looks like a "3" on its side'},
        4: {'repr': ['r'],
            'mnemonic': 'last letter of four, also 4 and R are almost mirror images of each other'},
        5: {'repr': ['l'],
            'mnemonic': 'L is the Roman Numeral for 50. Also, if you hold up your left hand, '
                        'your thumb and index fingers form an L, and you have five fingers.'},
        6: {'repr': ['j', 'sh', 'ch', 'soft g'],
            'mnemonic': 'a script j has a lower loop / g is almost a 6 rotated'},
        7: {'repr': ['k', 'hard c', 'hard g', 'hard ch', 'q'],
            'mnemonic': 'capital K "contains" two sevens (some variant systems include "ng" /ŋ/.)'},
        8: {'repr': ['f', 'v'],
            'mnemonic': 'script f resembles a figure-8. V sounds similar. (v is a voiced f)'},
        9: {'repr': ['p', 'b'],
            'mnemonic': 'p is a mirror-image 9. b sounds similar and resembles a 9 rolled around.'},
    },

    'ru': {
        0: {'repr': ['н'],
            'mnemonic': 'Ноль'},
        1: {'repr': ['к'],
            'mnemonic': '1 - Кол'},
        2: {'repr': ['л'],
            'mnemonic': 'Цифра 2 похожа на Лебедя'},
        3: {'repr': ['т'],
            'mnemonic': 'Три'},
        4: {'repr': ['ч'],
            'mnemonic': 'Четыре'},
        5: {'repr': ['п'],
            'mnemonic': 'Пять'},
        6: {'repr': ['ш', 'щ'],
            'mnemonic': 'Шесть. Буква Щ похожа на Ш.'},
        7: {'repr': ['с'],
            'mnemonic': 'Семь'},
        8: {'repr': ['в'],
            'mnemonic': 'Восемь'},
        9: {'repr': ['д'],
            'mnemonic': 'Девять'},
    },
}